### ISSUE TITLE
FileDownloadBehavior causes 500 when DownloadFileModel is null

### ISSUE THREAD

**Issue by KevM** [DarthFubuMVC/fubumvc#791]
I have an action which serves files but needs to do the right thing when the resource requested does not exist. The out of the box DownloadFileBehavior throws a 500 with a null reference exception when the `DownloadFileModel `output model is null. 

I replaced the behavior with the one below which checks for null but I am not sure if this is the best way to do this. It seems if I just DoNext.Continue without writing the file to output that a 200 is still returned so I added my own 404 behavior status response and stop the chain.

```cs
public class DownloadFileBehavior : BasicBehavior
{
	private readonly IFubuRequest _request;
	private readonly IOutputWriter _writer;

	public SeekerDownloadFileBehavior(IOutputWriter writer, IFubuRequest request)
		: base(PartialBehavior.Ignored)
	{
		_writer = writer;
		_request = request;
	}

	protected override DoNext performInvoke()
	{
		var output = _request.Get<DownloadFileModel>();

		if (output == null || output.LocalFileName.IsEmpty())
		{
			_writer.WriteResponseCode(HttpStatusCode.NotFound);
			return DoNext.Stop;
		}

		_writer.WriteFile(output.ContentType, output.LocalFileName, output.FileNameToDisplay);

		return DoNext.Continue;
	}
}
```

**Comment by jeremydmiller** [comment]
Moot point, I've eliminated the download behavior from 3+. In the Jasper timeframe, there are far more efficient OWIN based mechanisms. Honestly, it's easier to just do this directly against IHttpResponse anyway.
