### ISSUE TITLE
Diagnostics fails when developer tool window is not open

### ISSUE THREAD

**Issue by jmarnold** [DarthFubuMVC/fubumvc#798]
I can only get diagnostics to render (without js errors) when I've got Chrome developer tools open. Just filing this here before I dig in a little.

**Comment by jeremydmiller** [comment]
Which version are you using?

**Comment by jmeline** [comment]
I am experiencing the same issue on version 2.1.1.1951

**Comment by jeremydmiller** [comment]
@jmarnold @jmeline Can you try it with #2.1.1.1986? I changed the embedded JS to resolve the functions that periodically blow up differently. And do note that I have no earthly idea why it didn't work in the first place. It misses finding FubuDiagnosticsSection/View, right?

**Comment by jeremydmiller** [comment]
Never mind guys, I just moved the problem in a new build. I'm looking at this right now
