### ISSUE TITLE
Serenity should collect JS errors automatically

### ISSUE THREAD

**Issue by jeremydmiller** [DarthFubuMVC/fubumvc#932]
Adapt this from EH code:

``` javascript

'use strict';
/*globals console:true, ErrorCollector:true*/
if (typeof console === "undefined") {
    console = {
        log: function () { },
        debug: function () { },
        info: function () { },
        warn: function () { },
        error: function () { },
        trace: function () { }
    };
}

ErrorCollector = (function (global, console) {
    var self = {
        errors: [],
        registerError: function (msg) {
            self.errors.push(msg);
        }
    };

    var log = function (msg) {
        self.registerError(msg);
    };

    function decorateWithLog(callback) {
        return function(msg) {
            log(msg);
            if (callback) {
              global.onerror = log; //callback(msg);
            }
        };
    }

    global.onerror = decorateWithLog(global.onerror);

    console.error = decorateWithLog(console.error);
    console.warn = decorateWithLog(console.warn);

    return self;
})(window, console);


```

Have this JS code injected by OWIN middleware in Serenity. And then do something like:

Driver
                               .InjectJavascript("return ErrorCollector.errors")
                               .As<IEnumerable<object>>()
                               .Select(obj => new HtmlTag("pre").Text(obj.ToString()));

Add this too:

```
    public class JavascriptErrorProvider : Report
    {
        private readonly FubuMvcSystem _system;

        public JavascriptErrorProvider(FubuMvcSystem system)
        {
            _system = system;
        }

        public string ShortTitle
        {
            get { return "Javascript"; }
        }

        public int Count
        {
            get { return GenerateReports().Count(); }
        }

        public string ToHtml()
        {
            return GenerateReports().ToTagList().ToHtmlString();
        }

        public string Title
        {
            get { return "Javascript Errors"; }
        }

        public IEnumerable<HtmlTag> GenerateReports()
        {
            // todo handle any ErrorCollector is not defined errors properly
            try
            {
                return _system.Application.Driver
                               .InjectJavascript("return ErrorCollector.errors")
                               .As<IEnumerable<object>>()
                               .Select(obj => new HtmlTag("pre").Text(obj.ToString()));
            }
            catch (Exception)
            {
                return new List<HtmlTag>();
            }
        }
    }
```

**Comment by mtscout6** [comment]
I think that instead of only collecting the issues in JavaScript memory you should immediately push them to Storyteller. If you don't you'll lose them the second an action (like link tag click, or form post) triggers navigation to another page.

**Comment by jeremydmiller** [comment]
@mtscout6 What about collecting them automatically after a navigation? Still want a way to drive it on demand regardless.

**Comment by mtscout6** [comment]
The second you do a post redirect get you lose the previous pages errors.

**Comment by jeremydmiller** [comment]
We *might* be able to play with WebDriverEventListener to automatically capture JS errors just before and after any navigation.

**Comment by mtscout6** [comment]
I think you'll be in for a hard road ahead if you try that. WebDriver does not always have the best hooks into the browser for all possible ways that navigation can get triggered. I'd strongly recommend you push them up as soon as you get them and forget trying to figure out how to poll it. Pushing is generally easier than trying to pull in every edge case.

**Comment by jeremydmiller** [comment]
And we're just backing off to being able to manually collect javascript errors on demand.
